code/msbacklog/historiasUsuario/urls.py
from django.conf.urls import url
from .views import (
    ProyectoCrearView,
    ProyectoDetailView,
    ProyectoEditarView,
    ProyectoListView,        
    ProyectoDeleteView,
    HistoriaUsuarioCrearView,
    HistoriaUsuarioDetailView,
    HistoriaUsuarioEditarView,
    HistoriaUsuarioListView,        
    HistoriaUsuarioDeleteView,
    historiaUsuario_uploadfile,
    HistoriaDependenciaUdpateView,
)  

urlpatterns = [
        
    url(r'^proyecto-list/(?P<id_usuario>\d+)$', ProyectoListView.as_view(), name='list-proyecto'),
    url(r'^crear-proyecto/(?P<id_usuario>\d+)$', ProyectoCrearView.as_view(), name='create-proyecto'),    
    url(r'^editar-proyecto/(?P<id_usuario>\d+)/(?P<pk>\d+)$', ProyectoEditarView.as_view(), name='edit-proyecto'),
    url(r'^eliminar-proyecto/(?P<id_usuario>\d+)/(?P<pk>\d+)$', ProyectoDeleteView.as_view(), name='delete-proyecto'),
    url(r'^detalle-proyecto/(?P<pk>\d+)$', ProyectoDetailView.as_view(), name='detail-proyecto'),

    url(r'^historias-list/(?P<id_proyecto>\d+)$', HistoriaUsuarioListView.as_view(), name='list-historias'),
    url(r'^crear-historia/(?P<id_proyecto>\d+)$', HistoriaUsuarioCrearView.as_view(), name='create-historia'),    
    url(r'^editar-historia/(?P<id_proyecto>\d+)/(?P<pk>\d+)$', HistoriaUsuarioEditarView.as_view(), name='edit-historia'),
    url(r'^eliminar-historia/(?P<id_proyecto>\d+)/(?P<pk>\d+)$', HistoriaUsuarioDeleteView.as_view(), name='delete-historia'),
    url(r'^detalle-historia/(?P<pk>\d+)$', HistoriaUsuarioDetailView.as_view(), name='detail-historia'),    
    url(r'^cargar-historias/(?P<id_proyecto>\d+)$', historiaUsuario_uploadfile, name='load-historias'),
    url(r'^dependencias-historias/(?P<pk>\d+)$', HistoriaDependenciaUdpateView.as_view(), name='dependencias-historias'),
    
]

code/msbacklog/metricas/urls.py
from django.conf.urls import url
from .views import (
    MetricasEditarView,
)  

urlpatterns = [
            
    url(r'^calcular-metricas/(?P<pk>\d+)$', MetricasEditarView.as_view(), name='calculate-metrics'),    

]

code/msbacklog/msbacklog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from historiasUsuario.views import index, home, landing, contactos
from django.conf.urls.static import static
from msbacklog.settings import base


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', index, name='index'),
    url(r'^$', landing, name='landing'),
    url(r'^home/$', home, name='home'),
    url(r'^contacto/$', contactos, name='contacto'),
    url(r'^historias/', include('historiasUsuario.urls', namespace='historias')),
    url(r'^microservicios/', include('microservicios.urls', namespace='microservicios')),
    url(r'^metricas/', include('metricas.urls', namespace='metricas')),
    url(r'^algoritmos/', include('algoritmosAgrupamiento.urls', namespace='algoritmos')),
]

urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

code/msbacklog/historiasUsuario/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Proyecto, HistoriaUsuario, Dependencia_Historia
from django.forms import ModelForm

class ProyectoForm(ModelForm):    
    class Meta: 
        IDIOMA_CHOICES =( 
            ("en", "English"), 
            ("es", "Spanish"),         
        )        
        model = Proyecto
        
        fields = ['nombre', 'sigla', 'descripcion', 'usuario', 'idioma','es_publico']
        labels = {
            'nombre':'Name', 'sigla':'Abbreviation', 'idioma':'Language', 'descripcion':'Description', 'es_publico':'Is public'
        }
        widgets = { 'usuario':forms.HiddenInput(attrs={'readonly':'readonly'}),                                        
                    'idioma': forms.Select(choices = IDIOMA_CHOICES),
                    'descripcion':forms.Textarea(),                    
        }
        

    def clean(self):
        cleaned_data = super(ProyectoForm, self).clean()

class HistoriaUsuarioForm(ModelForm):
    class Meta: 
        model = HistoriaUsuario  
        fields = ['identificador', 'nombre', 'descripcion', 'prioridad', 'puntos_estimados', 'tiempo_estimado',
                    'escenario', 'observaciones', 'proyecto']
        labels = {
            'identificador':'ID','nombre':'Name', 'prioridad':'Priority', 'descripcion':'Description', 
            'puntos_estimados':'Estimated points', 'tiempo_estimado':'Estimated time', 'escenario':'Scenario',
            'observaciones':'Observations',
        }
        widgets = { 'proyecto':forms.HiddenInput(attrs={'readonly':'readonly'}),                    
                    'descripcion':forms.Textarea(),
                    'escenario':forms.Textarea(),
                    'observaciones':forms.Textarea(),                    
                  }

    def clean(self):
        cleaned_data = super(HistoriaUsuarioForm, self).clean() 

class UploadFileForm(forms.Form):    
    file = forms.FileField()

class HistoriaDependenciasForm(ModelForm):
    class Meta: 
        model = HistoriaUsuario 
        fields = ['escenario']
        labels = {
            'escenario':'Scenario',
        }
        widgets = { 'escenario':forms.Textarea(),                                        
                  }

    def clean(self):
        cleaned_data = super(HistoriaDependenciasForm, self).clean()

code/msbacklog/historiasUsuario/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from subprocess import call

from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import Proyecto, HistoriaUsuario, Usuario, Dependencia_Historia
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.db import IntegrityError
from django.views.generic.edit import (
    CreateView,
    UpdateView,    
    DeleteView,
)
from django.views.generic import ListView, DetailView
from django import forms
from .forms import ProyectoForm, HistoriaUsuarioForm, UploadFileForm, HistoriaDependenciasForm
import requests
import csv
import os

# Create your views here.
def contactos(request):
    return render(request, 'contacto.html')
    
def index(request):
    return render(request, 'index.html')

def home(request):
    return render(request, 'home.html')

def landing(request):
    return render(request, 'landing.html')

class ProyectoListView(ListView):
    model = Proyecto
    context_object_name = 'listaProyecto'

    def get_queryset(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])
        return Proyecto.objects.filter(usuario=self.usuario)

    def get_context_data(self, **kwargs): 
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])               
        context = super(ProyectoListView, self).get_context_data(**kwargs)      
        context['usuario'] = self.usuario        
        return context    

    def get_initial(self):    
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])            
        return { 'usuario': self.usuario}

class ProyectoCrearView(CreateView):
    model = Proyecto
    form_class = ProyectoForm    
    success_msg = "Project saved"

    def get_context_data(self, **kwargs): 
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])               
        context = super(ProyectoCrearView, self).get_context_data(**kwargs)      
        context['usuario'] = self.usuario        
        return context

    def get_initial(self):    
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])            
        return { 'usuario': self.usuario}
    
    def form_valid(self, form):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])
        proyecto = Proyecto(
            nombre = form.cleaned_data['nombre'],
            descripcion = form.cleaned_data['descripcion'],
            idioma = form.cleaned_data['idioma'],
            sigla = form.cleaned_data['sigla'],
            es_publico = form.cleaned_data['es_publico'],
            usuario = self.usuario,                        
        )
        proyecto.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])
        messages.success(self.request, self.success_msg)
        return  '/historias/proyecto-list/%s' % (self.usuario.id)    

class ProyectoEditarView(UpdateView):
    model = Proyecto
    form_class = ProyectoForm
    context_object_name = 'proyecto'    
    success_msg = "Proyect updated"

    def get_context_data(self, **kwargs):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        context = super(ProyectoEditarView, self).get_context_data(**kwargs)              
        context['usuario'] = self.usuario
        return context
    
    def get_initial(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        return { 'usuario': self.usuario }    
    
    def get_success_url(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])
        messages.success(self.request, self.success_msg)
        return  '/historias/proyecto-list/%s' % (self.usuario.id)

class ProyectoDeleteView(DeleteView):
    model = Proyecto 
    success_msg = "Project Deleted"
    protect_msg = "Cannot delete Project, some relation exists"   

    def get_context_data(self, **kwargs):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        context = super(ProyectoDeleteView, self).get_context_data(**kwargs)              
        context['usuario'] = self.usuario
        return context
    
    def get_initial(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        return { 'usuario': self.usuario }        
        
    def get_success_url(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])
        messages.success(self.request, self.success_msg)
        return  '/historias/proyecto-list/%s' % (self.usuario.id)
    
class ProyectoDetailView(DetailView):
    model = Proyecto
    context_object_name = 'proyecto'

class HistoriaUsuarioListView(ListView):
    model = HistoriaUsuario
    context_object_name = 'listaHistorias'

    def get_queryset(self):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])                      
        return HistoriaUsuario.objects.filter(proyecto = self.proyecto) 

    def get_context_data(self, **kwargs): 
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])               
        context = super(HistoriaUsuarioListView, self).get_context_data(**kwargs)      
        context['proyecto'] = self.proyecto        
        return context
    
    def get_initial(self):    
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])            
        return { 'proyecto': self.proyecto}

class HistoriaUsuarioCrearView(CreateView):
    model = HistoriaUsuario
    form_class = HistoriaUsuarioForm    
    success_msg = "User Story saved"
    exists_msg = "User Story already exists"

    def get_context_data(self, **kwargs): 
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])               
        context = super(HistoriaUsuarioCrearView, self).get_context_data(**kwargs)      
        context['proyecto'] = self.proyecto        
        return context

    def get_initial(self):    
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])            
        return { 'proyecto': self.proyecto}
    
    def form_valid(self, form):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])
        try:
            historia = HistoriaUsuario.objects.get(identificador=form.cleaned_data['identificador'])
            messages.error(self.request, self.exists_msg)
        except HistoriaUsuario.DoesNotExist:
            historia = HistoriaUsuario(
                identificador = form.cleaned_data['identificador'],
                nombre = form.cleaned_data['nombre'],
                descripcion = form.cleaned_data['descripcion'],
                prioridad = form.cleaned_data['prioridad'],
                puntos_estimados = form.cleaned_data['puntos_estimados'],
                tiempo_estimado = form.cleaned_data['tiempo_estimado'],
                escenario = form.cleaned_data['escenario'],
                observaciones = form.cleaned_data['observaciones'],
                proyecto = self.proyecto,                        
            )
            historia.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])
        messages.success(self.request, self.success_msg)
        return  '/historias/historias-list/%s' % (self.proyecto.id)    

class HistoriaUsuarioEditarView(UpdateView):
    model = HistoriaUsuario
    form_class = HistoriaUsuarioForm
    context_object_name = 'historia'    
    success_msg = "User Story updated"

    def get_context_data(self, **kwargs):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])        
        context = super(HistoriaUsuarioEditarView, self).get_context_data(**kwargs)              
        context['proyecto'] = self.proyecto
        return context
    
    def get_initial(self):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])        
        return { 'proyecto': self.proyecto }    
    
    def get_success_url(self):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])
        messages.success(self.request, self.success_msg)
        return  '/historias/historias-list/%s' % (self.proyecto.id)

class HistoriaUsuarioDeleteView(DeleteView):
    model = HistoriaUsuario 
    success_msg = "User Story Deleted"   

    def get_context_data(self, **kwargs):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])        
        context = super(HistoriaUsuarioDeleteView, self).get_context_data(**kwargs)              
        context['proyecto'] = self.proyecto
        return context
    
    def get_initial(self):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])        
        return { 'proyecto': self.proyecto }
        
    def get_success_url(self):
        self.proyecto = get_object_or_404(Proyecto, id=self.kwargs['id_proyecto'])
        messages.success(self.request, self.success_msg)
        return  '/historias/historias-list/%s' % (self.proyecto.id)

class HistoriaUsuarioDetailView(DetailView):
    model = HistoriaUsuario
    context_object_name = 'historia'

def historiaUsuario_uploadfile(request, **kwargs):            
    proyectoCarga = get_object_or_404(Proyecto, id= kwargs['id_proyecto'])
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            f = request.FILES['file']
            #fname = 'historias-' + str(proyectoCarga.id) + '.cvs'
            #call('sudo touch -m ' + fname)

code/msbacklog/templates/historiasUsuario/historiaUsuario_list.html
{% extends "base_list.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Create and manage the user stories{% endblock %}

<div class="box box-primary">    
    <div class="box-body">        
        <div class="row">            
            {% block cabecera_tabla %}
            <div class="box-header blue-border">
                <h2 class="box-title"><strong>Project: {{ proyecto.sigla }}</strong></h2>                
            </div>        
            <a href="{% url 'historias:create-historia' proyecto.id %}" title="Add User Storie">
                    <img src="{% static 'images/add_16.png'%}"/> Add User Storie
            </a>
            <br>    
            <br>
            <thead>
                <tr>
                    <th>Id.</th>
                    <th>Name</th>
                    <th>Priority</th>        
                    <th>Points</th>        
                    <th>Dev. time</th>
                    <th>Options</th>
                </tr>
                </thead>
            {% endblock cabecera_tabla %}
            {% block cuerpo_tabla %}                
                {%  if listaHistorias %}
                <tbody>
                    {% for historia in listaHistorias %}
                    
                        <tr>
                            <td><a href="{% url 'historias:detail-historia' historia.id %}" title="Details">{{ historia.id }}</a></td>                            
                            <td>{{ historia.nombre }}</td>
                            <td>{{ historia.prioridad }}</td>
                            <td>{{ historia.puntos_estimados }}</td>
                            <td>{{ historia.tiempo_estimado }}</td>                            
                            <td>
                                <a href="{% url 'historias:edit-historia' proyecto.id historia.id %}" title="Edit">
                                    <img src="{% static 'images/edit_16.png'%}"></img>
                                </a>
                                <a href="{% url 'historias:delete-historia' proyecto.id historia.id %}" title="Delete">
                                    <img src="{% static 'images/delete_16.png'%}"></img>
                                </a>                                                                
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                {% else %}
                <tbody>
                    <tr>
                        <td>There are not user stories</td>
                        <td></td>                        
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
                {% endif %}                               
            {% endblock cuerpo_tabla %}
            <div class="box-footer">
                <center>                                    
                    <a href="/historias/proyecto-list/{{usuario.id}}">
                            {% bootstrap_button "List projects" button_type="button" button_class="btn-primary"%}
                    </a>
                </center>                         
            </div>
        </div>
    </div>    
</div>

code/msbacklog/templates/historiasUsuario/historiausuario_confirm_delete.html
{% extends "base.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Delete User Storie {% endblock %}

{% block content %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Delete User Storie</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form method="post" class="form-horizontal" enctype="multipart/form-data">            
            <div class="box-body">
                <strong>User Storie: {{ object.nombre }}</strong>
                {% csrf_token %}                
            
                <!-- /.box-body -->
                <br>
                <br>                            
                <p>Are you sure to delete the user storie: <strong> {{ object.identificador }} ? </strong></p>
                <br>
                
            </div>
            <!-- /.box-footer -->
            <div class="box-footer">
                <center>
                    {% bootstrap_button "Confirm" button_type="submit" button_class="btn-primary"%}                                                    
                    <a href="{% url 'historias:list-historias' object.proyecto.id %}">
                        {% bootstrap_button "Cancel" button_type="button" button_class="btn-primary"%}
                    </a>
                </center>
            </div>
        </form>
    </div>    
{% endblock %}

code/msbacklog/templates/historiasUsuario/historiausuario_form.html
{% extends "base.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Create or update user storie {% endblock %}

{% block content %}

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Please insert the required data</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form method="post" class="form-horizontal" enctype="multipart/form-data">
            <div class="box-body">
                {% csrf_token %}
                {% bootstrap_form form layout="horizontal" %}
            </div>
            <!-- /.box-body -->
            <center>
                <div class="box-footer">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                    <a href="{% url 'historias:list-historias' object.proyecto.id %}">
                        {% bootstrap_button "Cancel" button_type="button" button_class="btn-primary"%}
                    </a>
                </div>
            </center>
            <!-- /.box-footer -->
        </form>
    </div>
{% endblock %}

code/msbacklog/templates/historiasUsuario/historiausuario_list.html
{% extends "base_list.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Create and manage the user stories{% endblock %}

<div class="box box-primary">    
    <div class="box-body">        
        <div class="row">                        
            {% block cabecera_tabla %}
            <div class="box-header blue-border">
                <h2 class="box-title"><strong>Project: {{ proyecto.sigla }}</strong></h2>                
            </div>        
            <div class="panel panel-info"> 
                <div class="panel-body"> 
                    <a href="{% url 'historias:create-historia' proyecto.id %}" title="Add User Storie">
                            <img src="{% static 'images/add_16.png'%}" width="24" height="24"/> Add User Storie
                    </a>  
                    <img src="{% static 'images/separator.png'%}"/>
                    <a href="{% url 'historias:load-historias' proyecto.id %}" title="Load User Storie from file">
                        <img src="{% static 'images/load-file.png'%}" width="24" height="24"/> Load from file
                    </a>
                </div>
            </div>                        
            <thead>
                <tr>
                    <th>Id.</th>
                    <th>Name</th>
                    <th>Priority</th>        
                    <th>Points</th>        
                    <th>Dev. time</th>
                    <th>Options</th>
                </tr>
                </thead>
            {% endblock cabecera_tabla %}
            {% block cuerpo_tabla %}                
                {%  if listaHistorias %}
                <tbody>
                    {% for historia in listaHistorias %}  
                    
                        <tr>
                            <td><a href="{% url 'historias:detail-historia' historia.id %}" title="Details">{{ historia.identificador }}</a></td>                            
                            <td>{{ historia.nombre }}</td>
                            <td>{{ historia.prioridad }}</td>
                            <td>{{ historia.puntos_estimados }}</td>
                            <td>{{ historia.tiempo_estimado }}</td>                            
                            <td>
                                <a href="{% url 'historias:edit-historia' proyecto.id historia.id %}" title="Edit">
                                    <img src="{% static 'images/edit_16.png'%}"></img>
                                </a>
                                <a href="{% url 'historias:delete-historia' proyecto.id historia.id %}" title="Delete">
                                    <img src="{% static 'images/delete_16.png'%}"></img>
                                </a>                                                                
                                <a href="{% url 'historias:dependencias-historias' historia.id %}" title="Dependencies">
                                    <img src="{% static 'images/dependencia.png'%}" width="16" height="16"/>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                {% else %}
                <tbody>
                    <tr>
                        <td>There are not user stories.</td>
                        <td></td>                        
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
                {% endif %}                               
            {% endblock cuerpo_tabla %}            
            {% block secondary_content %}
            <div class="panel panel-info"> 
                <div class="panel-body">   
                <center>      
                    <a href="{% url 'historias:list-proyecto' proyecto.usuario.id %}">
                            {% bootstrap_button "Return to projects" button_type="button" button_class="btn-primary"%}
                    </a>                      
                </center>
                </div>
            </div>
            {% endblock secondary_content %}
        </div>        
    </div>    
            
</div>

code/msbacklog/templates/historiasUsuario/historiausuario_upload.html
{% extends "base.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Load user storie from file{% endblock %}

{% block content %}

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Please upload CVS file.</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form method="post" class="form-horizontal" enctype="multipart/form-data">
            <div class="box-body">
                <strong>Proyecto: {{ proyecto.sigla }}</strong>
                {% csrf_token %}
                {% bootstrap_form form layout="horizontal" %}
            </div>
            <!-- /.box-body -->
            <center>
                <div class="box-footer">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                    <a href="{% url 'historias:list-historias' proyecto.id %}">
                        {% bootstrap_button "Cancel" button_type="button" button_class="btn-primary"%}
                    </a>
                </div>
            </center>
            <!-- /.box-footer -->
        </form>
    </div>
{% endblock %}

code/msbacklog/templates/historiasUsuario/proyecto_list.html
{% extends "base_list.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Create and manage the projects{% endblock %}

<div class="box box-primary">    
    <div class="box-body">        
        <div class="row">            
            {% block cabecera_tabla %}
            <div class="box-header blue-border">
                <h2 class="box-title"><strong>User: {{ usuario.nombre }}</strong></h2>
                <div class="box-title pull-right">                
                    <img class="img-circle" src="{% static 'images/perfil_defecto.png' %}" alt="Escudo" width="40" height="40">                
                </div>
            </div> 
            <div class="panel panel-info"> 
                <div class="panel-body">         
                    <a href="{% url 'historias:create-proyecto' usuario.id %}" title="Add Project">
                            <img src="{% static 'images/add_16.png'%}"/> Add Project
                    </a>
                </div>
            </div>            
            <thead>
                <tr>
                    <th>Abbr.</th>
                    <th>Name</th>        
                    <th>Public</th>
                    <th>User Stories</th>
                    <th>Points</th>        
                    <th>Options</th>
                </tr>
                </thead>
            {% endblock cabecera_tabla %}
            {% block cuerpo_tabla %}                
                {%  if listaProyecto %}
                <tbody>
                    {% for proyecto in listaProyecto %}
                    
                        <tr>
                            <td><a href="{% url 'historias:detail-proyecto' proyecto.id %}" title="Details">{{ proyecto.sigla }}</a></td>                            
                            <td>{{ proyecto.nombre }}</td>
                            <td>{{ proyecto.es_publico }}</td>
                            <td>{{ proyecto.getNumeroHistorias }}</td>
                            <td>{{ proyecto.getTotalPuntos }}</td>                            
                            <td>
                                <a href="{% url 'historias:edit-proyecto' usuario.id proyecto.id %}" title="Edit">
                                    <img src="{% static 'images/edit_16.png'%}"></img>
                                </a>
                                <a href="{% url 'historias:delete-proyecto' usuario.id proyecto.id %}" title="Delete">
                                    <img src="{% static 'images/delete_16.png'%}"></img>
                                </a>
                                <a href="{% url 'historias:list-historias' proyecto.id %}" title="User stories">
                                    <img src="{% static 'images/historias_16.png'%}" height="24" width="24"></img>
                                </a>                                
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                {% else %}
                <tbody>
                    <tr>
                        <td>There are not projects</td>
                        <td></td>                        
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
                {% endif %}                               
            {% endblock cuerpo_tabla %}
            {% block secondary_content %}
            <div class="panel panel-info"> 
                <div class="panel-body">   
                <center>
                    
                    <a href="/index/">
                            {% bootstrap_button "Return to index" button_type="button" button_class="btn-primary"%}
                    </a>
                </center>                         
                </div>
            </div>
            {% endblock secondary_content %}
        </div>
    </div>    
</div>