code/msbacklog/algoritmosAgrupamiento/urls.py
from django.conf.urls import url
from .views import (
    algoritmoClustering,
    clusteringCalls,
    algoritmoGenetico,
    compararDescomposiciones, algoritmoGeneticoInteroperabilidad,
)  

urlpatterns = [
            
    url(r'^clusterin-algortimo/(?P<pk>\d+)$', algoritmoClustering, name='clustering-algoritmo'),
    url(r'^clustering-calls/(?P<pk>\d+)$', clusteringCalls, name='clustering-calls'),    
    url(r'^algortimo-genetico/(?P<pk>\d+)$', algoritmoGenetico, name='algoritmo-genetico'),
    url(r'^compare-descompositions/(?P<pk>\d+)$', compararDescomposiciones, name='compare-descompositions'),
    url(r'^algortimo-genetico-interoperabilidad$', algoritmoGeneticoInteroperabilidad, name='algoritmo-genetico-interoperabilidad'),
    url(r'^algortimo-genetico-interoperabilidad/(?P<pk>\d+)$', algoritmoGeneticoInteroperabilidad, name='algoritmo-genetico-interoperabilidad'),
]

code/msbacklog/metricas/urls.py
from django.conf.urls import url
from .views import (
    MetricasEditarView,
)  

urlpatterns = [
            
    url(r'^calcular-metricas/(?P<pk>\d+)$', MetricasEditarView.as_view(), name='calculate-metrics'),    

]

code/msbacklog/microservicios/urls.py
from django.conf.urls import url
from .views import (
    MicroservicioAppCrearView,
    MicroservicioAppDeleteView,
    MicroservicioAppDetailView,
    MicroservicioAppListView,
    MicroservicioAppEditarView,
    MicroservicioCrearView,
    MicroservicioDeleteView, 
    MicroservicioDetailView, 
    MicroservicioEditarView,
    MicroserviciosHistoriaUdpateView,
    MicroserviciosListView,
    microservicesBacklogDiagram,
)  

urlpatterns = [
        
    url(r'^msapp-list/(?P<id_usuario>\d+)$', MicroservicioAppListView.as_view(), name='list-msapp'),
    url(r'^crear-msapp/(?P<id_usuario>\d+)$', MicroservicioAppCrearView.as_view(), name='create-msapp'),    
    url(r'^editar-msapp/(?P<id_usuario>\d+)/(?P<pk>\d+)$', MicroservicioAppEditarView.as_view(), name='edit-msapp'),
    url(r'^eliminar-msapp/(?P<id_usuario>\d+)/(?P<pk>\d+)$', MicroservicioAppDeleteView.as_view(), name='delete-msapp'),
    url(r'^detalle-msapp/(?P<pk>\d+)$', MicroservicioAppDetailView.as_view(), name='detail-msapp'),

    url(r'^microservicios-list/(?P<id_aplicacion>\d+)$', MicroserviciosListView.as_view(), name='list-microservicios'),
    url(r'^crear-microservicio/(?P<id_aplicacion>\d+)$', MicroservicioCrearView.as_view(), name='create-microservicio'),    
    url(r'^editar-microservicio/(?P<id_aplicacion>\d+)/(?P<pk>\d+)$', MicroservicioEditarView.as_view(), name='edit-microservicio'),
    url(r'^eliminar-microservicio/(?P<id_aplicacion>\d+)/(?P<pk>\d+)$', MicroservicioDeleteView.as_view(), name='delete-microservicio'),
    url(r'^detalle-microservicio/(?P<pk>\d+)$', MicroservicioDetailView.as_view(), name='detail-microservicio'),    
    #url(r'^cargar-microservicios/(?P<id_aplicacion>\d+)$', microservicios_uploadfile, name='load-microservicios'),
    url(r'^microservicios-historias/(?P<pk>\d+)$', MicroserviciosHistoriaUdpateView.as_view(), name='microservicios-historias'),
    url(r'^microservices-backlog/(?P<pk>\d+)$', microservicesBacklogDiagram, name='microservices-backlog'),
]

code/msbacklog/msbacklog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from historiasUsuario.views import index, home, landing, contactos
from django.conf.urls.static import static
from msbacklog.settings import base


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', index, name='index'),
    url(r'^$', landing, name='landing'),
    url(r'^home/$', home, name='home'),
    url(r'^contacto/$', contactos, name='contacto'),
    url(r'^historias/', include('historiasUsuario.urls', namespace='historias')),
    url(r'^microservicios/', include('microservicios.urls', namespace='microservicios')),
    url(r'^metricas/', include('metricas.urls', namespace='metricas')),
    url(r'^algoritmos/', include('algoritmosAgrupamiento.urls', namespace='algoritmos')),
]

urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

code/msbacklog/microservicios/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Microservicio, MicroservicioApp, Microservicio_Historia
from historiasUsuario.models import Proyecto
from django.forms import ModelForm

class MicroservicioAppForm(ModelForm):
    class Meta: 
        model = MicroservicioApp
        fields = ['nombre', 'metodo', 'proyecto', 'descripcion']
        labels = {
            'nombre':'Name', 'descripcion':'Description', 'metodo':'Method', 'proyecto':'Project',
        }
        widgets = {    
            'descripcion':forms.Textarea(),                    
        }

    def clean(self):
        cleaned_data = super(MicroservicioAppForm, self).clean()
    
    def __init__(self, *args, **kwargs):
        super(MicroservicioAppForm, self).__init__(*args, **kwargs)
        initial = kwargs['initial']
        self.fields['proyecto'].queryset = Proyecto.objects.filter(usuario=initial['usuario'])

class MicroservicioForm(ModelForm):
    class Meta: 
        model = Microservicio  
        fields = ['nombre', 'descripcion', 'aplicacion'
        ]
        labels = {
            'nombre':'Name', 'descripcion':'Description',
        }
        widgets = { 
            'aplicacion':forms.HiddenInput(attrs={'readonly':'readonly'}),                                        
            'descripcion':forms.Textarea(),
        }

    def clean(self):
        cleaned_data = super(MicroservicioForm, self).clean()

class MicroservicioHistoriasForm(ModelForm):
    class Meta: 
        model = Microservicio 
        fields = ['descripcion']
        labels = {
            'descripcion':'Description',
        }
        widgets = { 'descripcion':forms.Textarea(),                                        
                  }

    def clean(self):
        cleaned_data = super(MicroservicioHistoriasForm, self).clean()

code/msbacklog/microservicios/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from subprocess import call

from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from .models import MicroservicioApp, Microservicio, Microservicio_Historia
from historiasUsuario.models import Usuario, Proyecto, HistoriaUsuario, Dependencia_Historia
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.db import IntegrityError
from django.views.generic.edit import (
    CreateView,
    UpdateView,    
    DeleteView,
)
from django.views.generic import ListView, DetailView
from django import forms 
from .forms import MicroservicioAppForm, MicroservicioForm, MicroservicioHistoriasForm
from algoritmosAgrupamiento.models import Clustering
from random import randint
import requests

# Create your views here.
class MicroservicioAppListView(ListView):
    model = MicroservicioApp
    context_object_name = 'listaMsapp'

    def get_queryset(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        return MicroservicioApp.objects.filter(proyecto__usuario = self.usuario) 

    def get_context_data(self, **kwargs): 
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])               
        context = super(MicroservicioAppListView, self).get_context_data(**kwargs)      
        context['usuario'] = self.usuario        
        return context    

    def get_initial(self):    
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])            
        return { 'usuario': self.usuario}

class MicroservicioAppCrearView(CreateView):
    model = MicroservicioApp
    form_class = MicroservicioAppForm    
    success_msg = "Microservice App decomposition saved"
    metodo=""    

    def get_context_data(self, **kwargs): 
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        context = super(MicroservicioAppCrearView, self).get_context_data(**kwargs)      
        context['usuario'] = self.usuario        
        return context

    def get_initial(self):    
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])            
        self.proyectos = Proyecto.objects.filter(usuario = self.usuario)               
        return { 'usuario': self.usuario}
    
    def form_valid(self, form):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])
        msApp = MicroservicioApp(
            nombre = form.cleaned_data['nombre'],
            descripcion = form.cleaned_data['descripcion'],
            metodo = form.cleaned_data['metodo'],
            proyecto = form.cleaned_data['proyecto'],            
        )
        msApp.save()        
        self.metodo = form.cleaned_data['metodo']
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        messages.success(self.request, self.success_msg)        
        return  '/microservicios/msapp-list/%s' % (self.usuario.id)

class MicroservicioAppEditarView(UpdateView):
    model = MicroservicioApp
    form_class = MicroservicioAppForm
    context_object_name = 'msapp'    
    success_msg = "Microservice App decomposition updated"

    def get_context_data(self, **kwargs):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        context = super(MicroservicioAppEditarView, self).get_context_data(**kwargs)              
        context['usuario'] = self.usuario
        return context
    
    def get_initial(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        return { 'usuario': self.usuario }    
    
    def get_success_url(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])
        messages.success(self.request, self.success_msg)
        return  '/microservicios/msapp-list/%s' % (self.usuario.id)

class MicroservicioAppDeleteView(DeleteView):
    model = MicroservicioApp 
    success_msg = "Microservice App decomposition Deleted"
    protect_msg = "Cannot delete Microservice App decomposition, some relation exists"   

    def get_context_data(self, **kwargs):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        context = super(MicroservicioAppDeleteView, self).get_context_data(**kwargs)              
        context['usuario'] = self.usuario
        return context
    
    def get_initial(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])        
        return { 'usuario': self.usuario }        
        
    def get_success_url(self):
        self.usuario = get_object_or_404(Usuario, id=self.kwargs['id_usuario'])
        messages.success(self.request, self.success_msg)
        return  '/microservicios/msapp-list/%s' % (self.usuario.id)
    
class MicroservicioAppDetailView(DetailView):
    model = MicroservicioApp
    context_object_name = 'msapp'

    def get_context_data(self, **kwargs):
        msapp = get_object_or_404(MicroservicioApp, id=self.kwargs['pk'])
        self.microservicios = Microservicio.objects.filter(aplicacion = msapp)        
        context = super(MicroservicioAppDetailView, self).get_context_data(**kwargs)              
        context['microservicios'] = self.microservicios
        return context
    
    def get_initial(self):
        msapp = get_object_or_404(MicroservicioApp, id=self.kwargs['pk'])
        self.microservicios = Microservicio.objects.filter(aplicacion = msapp)
        return { 'microservicios': self.microservicios }

class MicroserviciosListView(ListView):
    model = Microservicio
    context_object_name = 'listams'

    def get_queryset(self):
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])        
        return Microservicio.objects.filter(aplicacion = self.aplicacion) 

    def get_context_data(self, **kwargs): 
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])                  
        context = super(MicroserviciosListView, self).get_context_data(**kwargs)      
        listams = Microservicio.objects.filter(aplicacion = self.aplicacion)
        context['aplicacion'] = self.aplicacion       
        return context
    
    def get_initial(self):    
        self.aplicacion = get_object_or_404(Proyecto, id=self.kwargs['id_aplicacion'])         
        listams = Microservicio.objects.filter(aplicacion = self.aplicacion)                            
        return { 'aplicacion': self.aplicacion, 'listams': listams}

class MicroservicioCrearView(CreateView):
    model = Microservicio
    form_class = MicroservicioForm    
    success_msg = "Microservice saved"
    exists_msg = "Microservice already exists"

    def get_context_data(self, **kwargs): 
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])               
        context = super(MicroservicioCrearView, self).get_context_data(**kwargs)      
        context['aplicacion'] = self.aplicacion        
        return context

    def get_initial(self):    
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])            
        return { 'aplicacion': self.aplicacion}
    
    def form_valid(self, form):
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])        
        
        ms = Microservicio(            
            nombre = form.cleaned_data['nombre'],
            descripcion = form.cleaned_data['descripcion'],            
            aplicacion = self.aplicacion,                        
        )
        ms.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])
        messages.success(self.request, self.success_msg)
        return  '/microservicios/microservicios-list/%s' % (self.aplicacion.id)    

class MicroservicioEditarView(UpdateView):
    model = Microservicio
    form_class = MicroservicioForm
    context_object_name = 'microservicio'    
    success_msg = "Microservice updated"

    def get_context_data(self, **kwargs):
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])        
        context = super(MicroservicioEditarView, self).get_context_data(**kwargs)              
        context['aplicacion'] = self.aplicacion
        return context
    
    def get_initial(self):
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])        
        return { 'aplicacion': self.aplicacion }    
    
    def get_success_url(self):
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])
        messages.success(self.request, self.success_msg)
        return  '/microservicios/microservicios-list/%s' % (self.aplicacion.id)

class MicroservicioDeleteView(DeleteView):
    model = Microservicio  
    success_msg = "Microservice Deleted"   

    def get_context_data(self, **kwargs):
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])        
        context = super(MicroservicioDeleteView, self).get_context_data(**kwargs)              
        context['aplicacion'] = self.aplicacion
        return context
    
    def get_initial(self):
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])        
        return { 'aplicacion': self.aplicacion }
        
    def get_success_url(self):
        self.aplicacion = get_object_or_404(MicroservicioApp, id=self.kwargs['id_aplicacion'])
        messages.success(self.request, self.success_msg)

code/msbacklog/templates/microservicios/microservicio_confirm_delete.html
{% extends "base.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Delete Microservice {% endblock %}

{% block content %}
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Delete Microservice</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form method="post" class="form-horizontal" enctype="multipart/form-data">            
            <div class="box-body">
                <strong>Microservice: {{ object.nombre }}</strong>
                {% csrf_token %}                
            
                <!-- /.box-body -->
                <br>
                <br>                            
                <p>Are you sure to delete the microservice: <strong> {{ object.identificador }} - {{ object.nombre }}? </strong></p>
                <br>
                
            </div>
            <!-- /.box-footer -->
            <div class="box-footer">
                <center>
                    {% bootstrap_button "Confirm" button_type="submit" button_class="btn-primary"%}                                                    
                    <a href="{% url 'microservicios:list-microservicios' object.aplicacion.id %}">
                        {% bootstrap_button "Cancel" button_type="button" button_class="btn-primary"%}
                    </a>
                </center>
            </div>
        </form>
    </div>    
{% endblock %}

code/msbacklog/templates/microservicios/microservicio_form.html
{% extends "base.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Create or update microservice {% endblock %}

{% block content %}

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Please insert the required data</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form method="post" class="form-horizontal" enctype="multipart/form-data">
            <div class="box-body">
                {% csrf_token %}
                {% bootstrap_form form layout="horizontal" %}
            </div>
            <!-- /.box-body -->
            <center>
                <div class="box-footer">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                    <a href="{% url 'microservicios:list-microservicios' aplicacion.id %}">
                        {% bootstrap_button "Cancel" button_type="button" button_class="btn-primary"%}
                    </a>
                </div>
            </center>
            <!-- /.box-footer -->
        </form>
    </div>
{% endblock %}

code/msbacklog/templates/microservicios/microservicio_list.html
{% extends "base_list.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Create and manage the microservices of the application{% endblock %}

<div class="box box-primary">    
    <div class="box-body">        
        <div class="row">                        
            {% block cabecera_tabla %}                        
            <div class="box-header blue-border">                
                <h2 class="box-title">
                    <strong>Project: {{ aplicacion.proyecto.sigla }}</strong><br>
                    <strong>Application: {{ aplicacion.nombre }}</strong>
                </h2>                
            </div>        
            <div class="panel panel-info"> 
                <div class="panel-body"> 
                    <a href="{% url 'microservicios:create-microservicio' aplicacion.id %}" title="Add Microservice">
                            <img src="{% static 'images/add_16.png'%}" width="24" height="24"/> Add Microservice
                    </a>                      
                </div>
            </div>
            <thead>
                <tr>                    
                    <th>Name</th>
                    <th>Number US.</th>
                    <th>User stories</th>        
                    <th>Points</th>        
                    <th>Dev. time</th>
                    <th>Options</th>
                </tr>
                </thead>
            {% endblock cabecera_tabla %}
            {% block cuerpo_tabla %}                
                {%  if listams %}
                <tbody>
                    {% for ms in listams %}  
                    
                        <tr>                             
                            <td><a href="{% url 'microservicios:detail-microservicio' ms.id %}" title="Details">{{ ms.nombre }}</a></td>
                            <td>{{ ms.numero_historias }}</td>
                            <td>
                                {% for hums in ms.getHistorias %}
                                    {{ hums.historia.identificador }} - {{ hums.historia.nombre }} <br>
                                {% endfor %}
                            </td>
                            <td>{{ ms.total_puntos }}</td>
                            <td>{{ ms.tiempo_estimado_desarrollo }}</td>                            
                            <td>
                                <a href="{% url 'microservicios:edit-microservicio' aplicacion.id ms.id %}" title="Edit">
                                    <img src="{% static 'images/edit_16.png'%}"></img>
                                </a>
                                <a href="{% url 'microservicios:delete-microservicio' aplicacion.id ms.id %}" title="Delete">
                                    <img src="{% static 'images/delete_16.png'%}"></img>
                                </a>
                                <a href="{% url 'microservicios:microservicios-historias' ms.id %}" title="User stories">
                                    <img src="{% static 'images/historias_16.png'%}" height="24" width="24"></img>
                                </a>                                                                                                
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                {% else %}
                <tbody>
                    <tr>
                        <td>There are not microservices.</td>
                        <td></td>                        
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
                {% endif %}                               
            {% endblock cuerpo_tabla %}            
            {% block secondary_content %}
            <div class="panel panel-info"> 
                <div class="panel-body">   
                <center>      
                    <a href="{% url 'microservicios:list-msapp' aplicacion.proyecto.usuario.id %}">
                            {% bootstrap_button "Return" button_type="button" button_class="btn-primary"%}
                    </a>                      
                </center>
                </div>
            </div>
            {% endblock secondary_content %}
        </div>        
    </div>    
            
</div>

code/msbacklog/templates/microservicios/microservicio_upload.html
{% extends "base.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Load microservices from file{% endblock %}

{% block content %}

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Please upload CVS file.</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form method="post" class="form-horizontal" enctype="multipart/form-data">
            <div class="box-body">
                <strong>Project: {{ aplicacion.proyecto.id }} - {{ aplicacion.proyecto.sigla}}</strong> <br>
                <strong>Application: {{ aplicacion.id }} - {{ aplicacion.nombre}}</strong>
                {% csrf_token %}
                {% bootstrap_form form layout="horizontal" %}
            </div>
            <!-- /.box-body -->
            <center>
                <div class="box-footer">
                    <input type="submit" value="Save" class="btn btn-primary"/>
                    <a href="{% url 'microservicios:list-microservicios' aplicacion.id %}">
                        {% bootstrap_button "Cancel" button_type="button" button_class="btn-primary"%}
                    </a>
                </div>
            </center>
            <!-- /.box-footer -->
        </form>
    </div>
{% endblock %}

code/msbacklog/templates/microservicios/microservicioapp_list.html
{% extends "base_list.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Create and manage microservices-based applications and decompositions{% endblock %}

<div class="box box-primary">    
    <div class="box-body">        
        <div class="row">                                    
            {% block cabecera_tabla %}
            <div class="box-header blue-border">
                <h2 class="box-title"><strong>Usuario: {{ usuario.nombre }}</strong></h2>
                <div class="box-title pull-right">                
                    <img class="img-circle" src="{% static 'images/perfil_defecto.png' %}" alt="User" width="40" height="40">                
                </div>
            </div> 
            <div class="panel panel-info"> 
                <div class="panel-body">         
                    <a href="{% url 'microservicios:create-msapp' usuario.id %}" title="Add microservices-based App.">
                            <img src="{% static 'images/add_16.png'%}" width="24" height="24"/> Add Microservices-based App.
                    </a>
                    <img src="{% static 'images/separator.png'%}"/>
                    <a href="{% url 'algoritmos:compare-descompositions' usuario.id %}" title="Compare decompositions">
                        <img src="{% static 'images/evaluar_16.png'%}" width="24" height="24"/> Evaluate Methods
                    </a>
                </div>
            </div>                        
            <thead>
                <tr>                    
                    <th>Name</th>
                    <th>Project</th>        
                    <th>Method</th>        
                    <th>GM</th>
                    <th>Options</th>
                </tr>
            </thead>
            {% endblock cabecera_tabla %}
            {% block cuerpo_tabla %}                
                {%  if listaMsapp %}
                <tbody>
                    {% for msapp in listaMsapp %}
                    
                        <tr>
                            <td><a href="{% url 'microservicios:detail-msapp' msapp.id  %}" title="Details">{{ msapp.nombre }}</a></td>                            
                            <td>{{ msapp.proyecto.nombre }}</td>
                            <td>{{ msapp.metodo.nombre }}</td>
                            <td>{{ msapp.valor_GM|floatformat:2 }}</td>                            
                            <td>
                                <a href="{% url 'microservicios:edit-msapp' usuario.id msapp.id %}" title="Edit">
                                    <img src="{% static 'images/edit_16.png'%}"></img>
                                </a>
                                <a href="{% url 'microservicios:delete-msapp' usuario.id msapp.id %}" title="Delete">
                                    <img src="{% static 'images/delete_16.png'%}"></img>
                                </a>
                                <a href="{% url 'microservicios:list-microservicios' msapp.id %}" title="Microservices">
                                    <img src="{% static 'images/servicios.png'%}"></img>
                                </a>
                                <a href="{% url 'metricas:calculate-metrics' msapp.id %}" title="Metrics">
                                    <img src="{% static 'images/metrics.png'%}"></img>
                                </a>
                                <a href="{% url 'microservicios:microservices-backlog' msapp.id %}" title="Microservices backlog diagram">
                                    <img src="{% static 'images/msbacklog-diagram2.png'%}"></img>
                                </a>
                                {%  if msapp.metodo.id == 1 %}
                                <a href="{% url 'algoritmos:algoritmo-genetico' msapp.id %}" title="Genetic programming">
                                    <img src="{% static 'images/genetico3.png'%}"></img>
                                </a>
                                {% endif %}
                                {%  if msapp.metodo.id == 2 %}
                                <a href="{% url 'algoritmos:clustering-algoritmo' msapp.id %}" title="Clustering">
                                    <img src="{% static 'images/cluster.png'%}"></img>
                                </a>       
                                {% endif %}                                                         
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
                {% else %}
                <tbody>
                    <tr>
                        <td>There are not microservices-based apps or decompositions</td>
                        <td></td>                        
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
                {% endif %}                               
            {% endblock cuerpo_tabla %}
            {% block secondary_content %}
            <div class="panel panel-info"> 
                <div class="panel-body">   
                <center>
                    
                    <a href="/index/">
                            {% bootstrap_button "Return to index" button_type="button" button_class="btn-primary"%}
                    </a>
                </center>                         
                </div>
            </div>
            {% endblock secondary_content %}
        </div>
    </div>    
</div>