code/msbacklog/algoritmosAgrupamiento/urls.py
from django.conf.urls import url
from .views import (
    algoritmoClustering,
    clusteringCalls,
    algoritmoGenetico,
    compararDescomposiciones, algoritmoGeneticoInteroperabilidad,
)  

urlpatterns = [
            
    url(r'^clusterin-algortimo/(?P<pk>\d+)$', algoritmoClustering, name='clustering-algoritmo'),
    url(r'^clustering-calls/(?P<pk>\d+)$', clusteringCalls, name='clustering-calls'),    
    url(r'^algortimo-genetico/(?P<pk>\d+)$', algoritmoGenetico, name='algoritmo-genetico'),
    url(r'^compare-descompositions/(?P<pk>\d+)$', compararDescomposiciones, name='compare-descompositions'),
    url(r'^algortimo-genetico-interoperabilidad$', algoritmoGeneticoInteroperabilidad, name='algoritmo-genetico-interoperabilidad'),
    url(r'^algortimo-genetico-interoperabilidad/(?P<pk>\d+)$', algoritmoGeneticoInteroperabilidad, name='algoritmo-genetico-interoperabilidad'),
]

code/msbacklog/metricas/urls.py
from django.conf.urls import url
from .views import (
    MetricasEditarView,
)  

urlpatterns = [
            
    url(r'^calcular-metricas/(?P<pk>\d+)$', MetricasEditarView.as_view(), name='calculate-metrics'),    

]

code/msbacklog/microservicios/urls.py
from django.conf.urls import url
from .views import (
    MicroservicioAppCrearView,
    MicroservicioAppDeleteView,
    MicroservicioAppDetailView,
    MicroservicioAppListView,
    MicroservicioAppEditarView,
    MicroservicioCrearView,
    MicroservicioDeleteView, 
    MicroservicioDetailView, 
    MicroservicioEditarView,
    MicroserviciosHistoriaUdpateView,
    MicroserviciosListView,
    microservicesBacklogDiagram,
)  

urlpatterns = [
        
    url(r'^msapp-list/(?P<id_usuario>\d+)$', MicroservicioAppListView.as_view(), name='list-msapp'),
    url(r'^crear-msapp/(?P<id_usuario>\d+)$', MicroservicioAppCrearView.as_view(), name='create-msapp'),    
    url(r'^editar-msapp/(?P<id_usuario>\d+)/(?P<pk>\d+)$', MicroservicioAppEditarView.as_view(), name='edit-msapp'),
    url(r'^eliminar-msapp/(?P<id_usuario>\d+)/(?P<pk>\d+)$', MicroservicioAppDeleteView.as_view(), name='delete-msapp'),
    url(r'^detalle-msapp/(?P<pk>\d+)$', MicroservicioAppDetailView.as_view(), name='detail-msapp'),

    url(r'^microservicios-list/(?P<id_aplicacion>\d+)$', MicroserviciosListView.as_view(), name='list-microservicios'),
    url(r'^crear-microservicio/(?P<id_aplicacion>\d+)$', MicroservicioCrearView.as_view(), name='create-microservicio'),    
    url(r'^editar-microservicio/(?P<id_aplicacion>\d+)/(?P<pk>\d+)$', MicroservicioEditarView.as_view(), name='edit-microservicio'),
    url(r'^eliminar-microservicio/(?P<id_aplicacion>\d+)/(?P<pk>\d+)$', MicroservicioDeleteView.as_view(), name='delete-microservicio'),
    url(r'^detalle-microservicio/(?P<pk>\d+)$', MicroservicioDetailView.as_view(), name='detail-microservicio'),    
    #url(r'^cargar-microservicios/(?P<id_aplicacion>\d+)$', microservicios_uploadfile, name='load-microservicios'),
    url(r'^microservicios-historias/(?P<pk>\d+)$', MicroserviciosHistoriaUdpateView.as_view(), name='microservicios-historias'),
    url(r'^microservices-backlog/(?P<pk>\d+)$', microservicesBacklogDiagram, name='microservices-backlog'),
]

code/msbacklog/msbacklog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from historiasUsuario.views import index, home, landing, contactos
from django.conf.urls.static import static
from msbacklog.settings import base


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', index, name='index'),
    url(r'^$', landing, name='landing'),
    url(r'^home/$', home, name='home'),
    url(r'^contacto/$', contactos, name='contacto'),
    url(r'^historias/', include('historiasUsuario.urls', namespace='historias')),
    url(r'^microservicios/', include('microservicios.urls', namespace='microservicios')),
    url(r'^metricas/', include('metricas.urls', namespace='metricas')),
    url(r'^algoritmos/', include('algoritmosAgrupamiento.urls', namespace='algoritmos')),
]

urlpatterns += static(base.MEDIA_URL, document_root=base.MEDIA_ROOT)

code/msbacklog/algoritmosAgrupamiento/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from microservicios.models import MicroservicioApp, Microservicio, Microservicio_Historia
from historiasUsuario.models import HistoriaUsuario, Dependencia_Historia
from .models import Clustering, Individuo, AlgoritmoGenetico
from historiasUsuario.models import Proyecto, Usuario
from django.http import JsonResponse
from metricas.models import Metrica
import json
from time import time

# Create your views here.  
def algoritmoClustering(request, **kwargs):
    if request.method == 'GET':
        msapp = get_object_or_404(MicroservicioApp, id=kwargs['pk'])        
        return render(request, 'algoritmosAgrupamiento/clustering.html', {'msapp': msapp})

    if request.method == 'POST':
        msapp = get_object_or_404(MicroservicioApp, id=kwargs['pk'])
        historias = HistoriaUsuario.objects.filter(proyecto = msapp.proyecto)        
        parametro = request.POST.get('parameter') # parametro de similitud semantecia
        coup_parametro = request.POST.get('coup_parameter')
        lenguaje = request.POST.get('lenguaje') 
        semantica_en = request.POST.get('semantic')
        modulo = request.POST.get('modulo')
        token = request.POST.get('token')        

        # Borrar las historias de los microservicios
        listMs = Microservicio.objects.filter(aplicacion = msapp)
        for ms in listMs:
            Microservicio_Historia.objects.filter(microservicio=ms).delete()

        #Borrar los microservicios que estaban antes
        if listMs:
            Microservicio.objects.filter(aplicacion = msapp).delete()
        
        # Agrupar las historias 
        startime = time()        
        cluster = Clustering(lenguaje, modulo)        
        lista = cluster.identificarEntidadHistorias(historias)
        lista2 = cluster.agruparPorFrecuenciaEntidad(lista, float(parametro), semantica_en)
        dura = time() - startime
        ##lista = cluster.calcularSimilitud(historias, semantica_en)
        ##dato = cluster.agruparHistorias(lista, len(historias),float(parametro))
        mensaje =  "<div id='divHUAsociadas' class='panel panel-primary'>"
        mensaje += "<div class='panel-heading'>Microservices grouped by semantic similarity</div>"
        mensaje += "<div class='panel-body'>"
        mensaje += "<table class='table table-striped table-bordered'>"
        mensaje += "<thead>"
        mensaje += "<tr>"
        mensaje += "<th>Microservice</th>"
        mensaje += "<th>User stories</th>"
        mensaje += "<th>Number of stories</th>"
        mensaje += "</tr>"
        mensaje += "</thead>"
        mensaje += "<tbody> "
        mensaje += "<tr>"
        mensaje += "<td colspan='3'>"
        mensaje += "Microservices: " + str(len(lista2))
        mensaje += "<br>Execution time: " + str(round(dura,3))
        mensaje += "</td>"
        mensaje += "</tr>"

        # for dato in lista:
        #     hu = dato[0]
        #     text = dato[1]
        #     lemma = dato[2]
        #     mensaje += "<tr>"
        #     mensaje += "<td>"
        #     mensaje += hu.identificador + " - " + hu.nombre + "<br>" + hu.descripcion
        #     #mensaje += hu #+ " - " + hu.nombre + "<br>" + hu.descripcion
        #     mensaje += "</td>"            
        #     mensaje += "<td>"
        #     mensaje += str(text)
        #     mensaje += "</td>"
        #     mensaje += "<td>"
        #     mensaje += str(lemma)
        #     mensaje += "</td>"
        #     mensaje += "</tr>"


        i=1
        for ms in lista2:
            nombre = "MS - " + ms[0][1]
            mensaje += "<tr>"
            mensaje += "<td>"
            mensaje += nombre
            mensaje += "</td>"
            mensaje += "<td>"
            suma = 0.0
            cont = 0

            for dato in ms:                
                historia = dato[0]
                mensaje += historia.identificador + " - " + historia.nombre + "<br>"                
                cont += 1            
            mensaje += "</td>"
            #avg = suma / cont
            mensaje += "<td>"
            mensaje += str(cont) 
            mensaje += "</td>"
            mensaje += "</tr>"           
                         
            # Guardar en la base de datos la descomposicion
            micro = Microservicio(
                nombre = nombre,
                numero_historias = cont,
                similitud_semantica = 0,
                aplicacion = msapp
            )
            micro.save()

            for dato in ms:
                hu = dato[0]
                ms_hu = Microservicio_Historia(
                    microservicio = micro,
                    historia = hu
                )
                ms_hu.save()
            i += 1
        mensaje += "</tbody> "
        mensaje += "</table>"
        mensaje += "</div>"
        mensaje += "</div>"
        mensaje += "</div>"
        mensaje += "<div class='box-footer'>"
        mensaje += "<center>"
        mensaje += "<form method='post' id='frmClusteringCalls' name='frmClusteringCalls' data-post-url='/algoritmos/clustering_calls/" + str(msapp.id) + "' class='form-horizontal' enctype='multipart/form-data'>" 
        mensaje +=  "<input type='hidden' name='csrfmiddlewaretoken' value='nE6GZ9xyyhCoTAbGBK4ah9L1NEnqO1AL4VoYicImxP5Ru8yYhLwg2waAIqmCrQri' />"
        mensaje += "<input type='hidden' id='msapp' name='msapp' value='" + str(msapp.id) + "'>"
        mensaje += "<input type='hidden' id='param' name='param' value='" + parametro + "'>"
        mensaje += "<input type='hidden' id='leng' name='leng' value='" + lenguaje + "'>"
        mensaje += "<input type='hidden' id='mdlo' name='mdlo' value='" + modulo + "'>"
        mensaje += "<input type='hidden' id='coup_param' name='coup_param' value='" + coup_parametro + "'>"    
        mensaje += "<input type='hidden' id='semantic' name='semantic' value='" + semantica_en + "'>"
        mensaje += "<input type='button' id='btnRequest' name='btnRequest' value='Group by Coupling Metrics'  onclick='clustercalls()' class='btn btn-primary'/>"                
        mensaje += "   <input type='button' id='btnCancelar' name='btnCancelar' value='Cancel' onclick='regresar()' class='btn btn-primary'/>"
        mensaje += "</form>"        
        mensaje += "</center>"
        mensaje += "</div>"        

        # Calcular las métricas
        metrica = Metrica()
        metrica.calcularMetricas(msapp)

        #return render(request, 'algoritmosAgrupamiento/clustering.html', {'msapp': aplicacion, 'lista': lista, 'dato':dato, })
        return JsonResponse({ 'content': { 'message': str(mensaje) } })
    messages.success(request, 'Error in GET method')
    return render(request, 'index.html')

def clusteringCalls(request, **kwargs):
    if request.method == 'GET':
        msapp = get_object_or_404(MicroservicioApp, id=kwargs['pk'])
        lenguaje = request.GET.get('leng') 
        parametro = request.GET.get('param')
        modulo = request.GET.get('mdlo')                        
        coup_parametro = request.GET.get('coup_parameter')   
        semantica_en = request.GET.get('semantica')

        print('------ semantica_en: ' +  str(semantica_en))

        cluster = Clustering(lenguaje, modulo) 
        startime = time()                                                    
        #simil_param = (float(parametro) - 0.05)
        simil_param = float(parametro)
        #datos = cluster.calcularDistanciaCoupling(msapp)
        #microservicios = Microservicio.objects.filter(aplicacion = msapp)        
        #listaMs = cluster.agruparMicroservicios(datos, len(microservicios), float(coup_parametro) )
        #matrizMSHU = cluster.generarGrupoMS(listaMs) 
        matrizMSHU = cluster.reAgruparMicroservicios(msapp, float(coup_parametro), simil_param, semantica_en )        
        dura = time() - startime
        # Borrar las historias de los microservicios
        lista = Microservicio.objects.filter(aplicacion = msapp)
        for ms in lista:
            Microservicio_Historia.objects.filter(microservicio=ms).delete()

        #Borrar los microservicios que estaban antes
        if lista:
            Microservicio.objects.filter(aplicacion = msapp).delete()
        
        #numero =0
         # Calcular las métricas        
        
        mensaje =  "<div id='divMSCoupling' class='panel panel-primary'>"
        mensaje += "<div class='panel-heading'>Microservices Grouped by Coupling Metrics</div>"
        mensaje += "<div class='panel-body'>"
        mensaje += "<table class='table table-striped table-bordered'>"
        mensaje += "<thead>"
        mensaje += "<tr>"
        mensaje += "<th>Microservice</th>"
        mensaje += "<th>User Stories</th>"        
        mensaje += "</tr>"
        mensaje += "</thead>"
        mensaje += "<tbody> "
        mensaje += "<tr>"
        mensaje += "<td colspan='2'>"
        mensaje += "Microservices: " + str(len(matrizMSHU))
        mensaje += "<br>Execution time: " + str(round(dura,3))
        mensaje += "<br>Similarity param: " + str(round(simil_param,3))
        mensaje += "</td>"
        mensaje += "</tr>"
        
        for dato in matrizMSHU:
            #nombreMS = dato[0]
            micro= dato[0]
            #cont = len(dato[1])
            mensaje += "<tr>"
            mensaje += "<td>"
            mensaje += micro.nombre
            mensaje += "<br>SIY: "+ str(micro.siy)
            mensaje += "</td>"
            mensaje += "<td>"

            # Guardar en la base de datos la descomposicion
            # micro = Microservicio(
            #     nombre = nombreMS,
            #     numero_historias = cont,                
            #     aplicacion = msapp
            # )

code/msbacklog/templates/algoritmosAgrupamiento/clustering.html
{% extends "base.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Clustering Algorithm - Group user stories in Microservices{% endblock %}

{% block content %}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Project: {{ msapp.proyecto.nombre }}</h2><br>            
            <h2 class="box-title">Application: {{ msapp.nombre }}</h2>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <div class="box-body">                                            
            <div class="panel panel-info">                                                       
                <div class="panel-heading"><strong> Clustering Algorithm parameters </strong></div>
                <div class="panel-body">                    
                    <form method="post" id="frmClustering" name="frmClustering" data-post-url="{% url 'algoritmos:clustering-algoritmo' msapp.id %}" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td><strong>Method:</strong></td>
                                    <td>
                                        <input type="text" id="metodo" name="metodo" value="{{ msapp.metodo.nombre }}" readonly="readonly" class="form-control"/>                                        
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>Similarity Grouper parameter:</strong></td>
                                    <td>
                                        <input type="number" id="parameter" name="parameter"  min="0.50" max="1.00" step="0.05" value="0.85" class="form-control"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>Coupling Grouper parameter:</strong></td>
                                    <td>
                                        <input type="number" id="coup_parameter" name="coup_parameter"  min="0.30" max="1.00" step="0.05" value="0.50" class="form-control"/>
                                    </td>
                                </tr>                            
                                <tr>
                                    <td><strong>Text language:</strong></td>
                                    <td>
                                        <select id="lenguaje" name="lenguaje" class="form-control" >
                                            <option value="es" selected>Spanish</option>
                                            <option value="en">English</option>                                            
                                        </select>                                
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>Semantic similarity on:</strong></td>
                                    <td>
                                        <select id="semantic" name="semantic" class="form-control" >
                                            <option value="lemma" >Lemmatization of entities</option>
                                            <option value="text" selected>Text of entities</option>                                                                                        
                                        </select>                                
                                    </td>
                                </tr>
                                <tr>
                                    <td><strong>Spacy module: </strong></td>
                                    <td>
                                        <select id="modulo" name="modulo" class="form-control" >
                                            <option value="sm">Small (Faster)</option>
                                            <option value="md" selected>Medium (More precise)</option>                                                                                        
                                        </select>                                
                                    </td>
                                </tr>                                         
                            </tbody>
                        </table>
                        <center>
                            <div class="box-footer">
                                <input type="hidden" id="token" name="token" value="{{ csrf_token }}" readonly="readonly" class="form-control"/>
                                <input type="submit" id="btnGenerar" name="btnGenerar" value="Group by Semantic Similarity" class="btn btn-primary"/>
                                <a href="{% url 'microservicios:list-msapp' msapp.proyecto.usuario.id %}">
                                    {% bootstrap_button "Cancel" button_type="button" button_class="btn-primary"%}
                                </a>
                            </div>
                        </center>
                    </form>                                                            
                </div>
            </div>            
            <div id="divResultado">

            </div>
            <div id="divResultadoCalls">

            </div>
        </div>                        
    </div>
{% endblock %}
{% block specific-js %}
    <script>
        
        $('#frmClustering').on( 'submit', function(){
            txtHtml = "<center>";
            txtHtml += "<div class='panel panel-warning'>";
            txtHtml += "<div class='panel-heading'>"
            txtHtml += "Grouping user stories by semantic similarity...";
            txtHtml += "</div>";
            txtHtml += "<div class='panel-body'>";
            txtHtml += "<img class='img-circle' alt='Loading' src='/static/images/cargando.gif' width='50' height='50'>";            
            txtHtml += "</div>";
            txtHtml += "</div>";
            txtHtml += "</center>";

            errHtml = "<center>";
            errHtml += "<div class='panel panel-danger'>";
            errHtml += "<div class='panel-heading'>"
            errHtml += "Failed to group user stories in microservices.";
            errHtml += "</div>";
            errHtml += "<div class='panel-body'>";
            errHtml += "<img class='img-circle' alt='Error' src='/static/images/error_16.png' width='50' height='50'>";            
            errHtml += "</div>";
            errHtml += "</div>";
            errHtml += "</center>";

            $('#divResultado').html(txtHtml);            
            
            var post_url = $('#frmClustering').data("post-url");
            var formData = new FormData(this);

            $.ajax({
                url: post_url,
                type: "POST", 
                data: formData,
                processData: false,
                contentType: false,

                success:function(response){
                    $('#divResultado').html(response.content.message);
                },

                error: function (response) {                    
                    $('#divResultado').html(errHtml);
                }

            });

            return false;
        });
                
    </script>    
    <script>
        function regresar(){            
            location.href = "{% url 'microservicios:list-msapp' msapp.proyecto.usuario.id %}";
        }        

        function clustercalls(){
            
            txtHtml = "<center>";
            txtHtml += "<div class='panel panel-warning'>";
            txtHtml += "<div class='panel-heading'>"
            txtHtml += "Calculating calls between Microservices then group them...";
            txtHtml += "</div>";
            txtHtml += "<div class='panel-body'>";
            txtHtml += "<img class='img-circle' alt='Loading' src='/static/images/cargando.gif' width='50' height='50'>";            
            txtHtml += "</div>";
            txtHtml += "</div>";
            txtHtml += "</center>";

            errHtml = "<center>";
            errHtml += "<div class='panel panel-danger'>";
            errHtml += "<div class='panel-heading'>"
            errHtml += "Failed to group microservices by coupling metrics.";
            errHtml += "</div>";
            errHtml += "<div class='panel-body'>";
            errHtml += "<img class='img-circle' alt='Loading' src='/static/images/error_16.png' width='20' height='20'>";  
            errHtml += "<br>System Error";
            errHtml += "</div>";
            errHtml += "</div>";
            errHtml += "</center>";

            $('#divResultadoCalls').html(txtHtml);            
            
            var post_url = "{% url 'algoritmos:clustering-calls' msapp.id %}";
            var formulario = $('#frmClusteringCalls')            
            var msapp = frmClusteringCalls.msapp.value;
            var param = frmClusteringCalls.param.value;
            var leng = frmClusteringCalls.leng.value;
            var mdlo = frmClusteringCalls.mdlo.value;
            var coup_parameter = frmClusteringCalls.coup_param.value;
            var coup_parameter = frmClusteringCalls.coup_param.value;
            var semantica = frmClusteringCalls.semantic.value;                
                           
            post_url += '?coup_parameter=' + coup_parameter + '&param='+param + '&semantica='+ semantica + '&leng='+ leng + '&mdlo='+ mdlo;
            $.ajax({
                url: post_url,                
                type: "GET", 
                dataType: 'json',
                data: {'msapp': msapp, 'param': param, 'leng':leng, 'mdlo': mdlo, 'coup_parameter': coup_parameter, 'param':param, "semantica":semantica },
                processData: false,
                contentType: false,

                success:function(response){
                    $('#divResultadoCalls').html(response.content.message);
                },

                error: function (response) {                    
                    $('#divResultadoCalls').html(errHtml);
                }
            });

            return false;
        }
    </script>
{% endblock %}

code/msbacklog/templates/algoritmosAgrupamiento/compare.html
{% extends "base.html" %}
{# Load the tag library #}
{% load staticfiles %}
{% load bootstrap3 %}

{% block page-title %}Microservices Backlog{% endblock %}
{% block page-description %}Genetic Algorithm - Group user stories in Microservices{% endblock %}

{% block specific-css %}
    <link href="{% static 'AdminLTE-2.3.11/plugins/datatables/dataTables.bootstrap.css' %}" rel="stylesheet">    
{% endblock %}

{% block content %}
    <div class="box box-primary">
        <div class="box-header with-border">
            <h2 class="box-title">Usuario: {{ usuario.nombre }}</h2>            
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <div class="box-body">                                            
            <div class="panel panel-info">                                                       
                <div class="panel-heading"><strong> Evaluate Decomposition Methods </strong></div>
                <div class="panel-body">                    
                    <form method="post" id="frmEvaluar" name="frmEvaluar" data-post-url="{% url 'algoritmos:compare-descompositions' usuario.id %}" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
                        <table class="table">
                            <tbody>                                                                                                            
                                <tr>
                                    <td><strong>Project:</strong></td>
                                    <td>
                                        {%  if proyectos %}
                                        <select id="proyecto" name="proyecto" class="form-control"|>
                                            {% for p in proyectos %}
                                                <option value="{{ p.id }}">{{p.sigla}}</option>
                                            {% endfor %}                                            
                                        </select>   
                                        {% else %}
                                            There are not projects.
                                        {% endif %}                             
                                    </td>
                                </tr>                                                                                                         
                            </tbody>
                        </table>
                        <center>
                            <div class="box-footer">
                                <input type="hidden" id="token" name="token" value="{{ csrf_token }}" readonly="readonly" class="form-control"/>
                                <input type="submit" id="btnEjecutar" name="btnEjecutar" value="Evaluate Methods" class="btn btn-primary"/>
                                <a href="{% url 'microservicios:list-msapp' usuario.id %}">
                                    {% bootstrap_button "Cancel" button_type="button" button_class="btn-primary"%}
                                </a>
                            </div>
                        </center>
                    </form>                                                            
                </div>
            </div>            
            <div id="divResultado">

            </div>
        </div>                        
    </div>
{% endblock %}
{% block specific-js %}
    <script src="{% static 'AdminLTE-2.3.11/plugins/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'AdminLTE-2.3.11/plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
    <script>
        
        $('#frmEvaluar').on( 'submit', function(){
            
            txtHtml = "<center>";
            txtHtml += "<div class='panel panel-warning'>";
            txtHtml += "<div class='panel-heading'>"
            txtHtml += "Evaluating Decompositons Methods...";
            txtHtml += "</div>";
            txtHtml += "<div class='panel-body'>";
            txtHtml += "<img class='img-circle' alt='Loading' src='/static/images/cargando.gif' width='50' height='50'>";            
            txtHtml += "</div>";
            txtHtml += "</div>";
            txtHtml += "</center>";

            errHtml = "<center>";
            errHtml += "<div class='panel panel-danger'>";
            errHtml += "<div class='panel-heading'>"
            errHtml += "Failed to evaluate decompositions methods.";
            errHtml += "</div>";
            errHtml += "<div class='panel-body'>";
            errHtml += "<img class='img-circle' alt='Error' src='/static/images/error_16.png' width='20' height='20'>";            
            errHtml += "</div>";
            errHtml += "</div>";
            errHtml += "</center>";

            $('#divResultado').html(txtHtml);            
            
            var post_url = $('#frmEvaluar').data("post-url");
            var formData = new FormData(this);            

            $.ajax({
                url: post_url,
                type: "POST", 
                data: formData,
                processData: false,
                contentType: false,

                success:function(response){
                    $('#divResultado').html(response.content.message);
                },

                error: function (response) {                    
                    $('#divResultado').html(errHtml);
                }

            });

            return false;
        });
                
    </script>    
    <script>
        function regresar(){            
            location.href = "{% url 'microservicios:list-msapp' usuario.id %}";
        }                        
    </script>
{% endblock %}